const escapePdfText = (value) =>
  String(value ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/[^\x20-\x7E]/g, "?");

const buildStream = (lines) => {
  const output = ["BT", "/F1 11 Tf", "50 780 Td"];

  lines.forEach((line, index) => {
    if (index > 0) {
      output.push("0 -16 Td");
    }
    output.push(`(${escapePdfText(line)}) Tj`);
  });

  output.push("ET");
  return output.join("\n");
};

export const createElectionResultsPdfBuffer = ({
  electionTitle,
  schoolName,
  electionDate,
  generatedAt,
  totalVotes,
  categorySummaries,
}) => {
  const lines = [
    `Election title: ${electionTitle}`,
    `Election date: ${electionDate}`,
    `School name: ${schoolName}`,
    `Total votes: ${totalVotes}`,
    "",
  ];

  categorySummaries.forEach((category) => {
    lines.push(`Category: ${category.title}`);
    category.rows.forEach((row) => {
      lines.push(
        `- ${row.name}: ${row.voteCount} votes (${row.percentage}%)${row.isWinner ? " WINNER" : ""}`
      );
    });
    lines.push("");
  });

  lines.push(`Generated by MyUniVote at ${generatedAt}`);

  const stream = buildStream(lines);
  const objects = [
    "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
    "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
    "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj",
    "4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
    `5 0 obj << /Length ${Buffer.byteLength(stream, "utf8")} >> stream\n${stream}\nendstream endobj`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];

  objects.forEach((object) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${object}\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";

  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }

  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, "utf8");
};
